name: mirroring

on: [ push, delete ]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: 'https://github.com/Hedius/clickhouse-backup.git'
          destination-repo: 'git@gitlab.com:Hedius/clickhouse-backup.git'